/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChileRouteImport } from './routes/_authenticated/chile'
import { Route as AuthenticatedCombustibleRouteImport } from './routes/_authenticated/combustible'
import { Route as AuthenticatedComunicacionesRouteImport } from './routes/_authenticated/comunicaciones'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedFlotaRouteImport } from './routes/_authenticated/flota'
import { Route as AuthenticatedFronterasRouteImport } from './routes/_authenticated/fronteras'
import { Route as AuthenticatedPlanificacionRouteImport } from './routes/_authenticated/planificacion'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChileRoute = AuthenticatedChileRouteImport.update({
  id: '/chile',
  path: '/chile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCombustibleRoute =
  AuthenticatedCombustibleRouteImport.update({
    id: '/combustible',
    path: '/combustible',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacionesRoute =
  AuthenticatedComunicacionesRouteImport.update({
    id: '/comunicaciones',
    path: '/comunicaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlotaRoute = AuthenticatedFlotaRouteImport.update({
  id: '/flota',
  path: '/flota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFronterasRoute = AuthenticatedFronterasRouteImport.update({
  id: '/fronteras',
  path: '/fronteras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanificacionRoute =
  AuthenticatedPlanificacionRouteImport.update({
    id: '/planificacion',
    path: '/planificacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/chile': typeof AuthenticatedChileRoute
  '/combustible': typeof AuthenticatedCombustibleRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/flota': typeof AuthenticatedFlotaRoute
  '/fronteras': typeof AuthenticatedFronterasRoute
  '/planificacion': typeof AuthenticatedPlanificacionRoute
  '/reportes': typeof AuthenticatedReportesRoute
}
export interface FileRoutesByTo {
  '/chile': typeof AuthenticatedChileRoute
  '/combustible': typeof AuthenticatedCombustibleRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/flota': typeof AuthenticatedFlotaRoute
  '/fronteras': typeof AuthenticatedFronterasRoute
  '/planificacion': typeof AuthenticatedPlanificacionRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/chile': typeof AuthenticatedChileRoute
  '/_authenticated/combustible': typeof AuthenticatedCombustibleRoute
  '/_authenticated/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/flota': typeof AuthenticatedFlotaRoute
  '/_authenticated/fronteras': typeof AuthenticatedFronterasRoute
  '/_authenticated/planificacion': typeof AuthenticatedPlanificacionRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chile'
    | '/combustible'
    | '/comunicaciones'
    | '/configuracion'
    | '/flota'
    | '/fronteras'
    | '/planificacion'
    | '/reportes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chile'
    | '/combustible'
    | '/comunicaciones'
    | '/configuracion'
    | '/flota'
    | '/fronteras'
    | '/planificacion'
    | '/reportes'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/chile'
    | '/_authenticated/combustible'
    | '/_authenticated/comunicaciones'
    | '/_authenticated/configuracion'
    | '/_authenticated/flota'
    | '/_authenticated/fronteras'
    | '/_authenticated/planificacion'
    | '/_authenticated/reportes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chile': {
      id: '/_authenticated/chile'
      path: '/chile'
      fullPath: '/chile'
      preLoaderRoute: typeof AuthenticatedChileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/combustible': {
      id: '/_authenticated/combustible'
      path: '/combustible'
      fullPath: '/combustible'
      preLoaderRoute: typeof AuthenticatedCombustibleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicaciones': {
      id: '/_authenticated/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof AuthenticatedComunicacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flota': {
      id: '/_authenticated/flota'
      path: '/flota'
      fullPath: '/flota'
      preLoaderRoute: typeof AuthenticatedFlotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fronteras': {
      id: '/_authenticated/fronteras'
      path: '/fronteras'
      fullPath: '/fronteras'
      preLoaderRoute: typeof AuthenticatedFronterasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planificacion': {
      id: '/_authenticated/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof AuthenticatedPlanificacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChileRoute: typeof AuthenticatedChileRoute
  AuthenticatedCombustibleRoute: typeof AuthenticatedCombustibleRoute
  AuthenticatedComunicacionesRoute: typeof AuthenticatedComunicacionesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedFlotaRoute: typeof AuthenticatedFlotaRoute
  AuthenticatedFronterasRoute: typeof AuthenticatedFronterasRoute
  AuthenticatedPlanificacionRoute: typeof AuthenticatedPlanificacionRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChileRoute: AuthenticatedChileRoute,
  AuthenticatedCombustibleRoute: AuthenticatedCombustibleRoute,
  AuthenticatedComunicacionesRoute: AuthenticatedComunicacionesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedFlotaRoute: AuthenticatedFlotaRoute,
  AuthenticatedFronterasRoute: AuthenticatedFronterasRoute,
  AuthenticatedPlanificacionRoute: AuthenticatedPlanificacionRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
